version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: corelia
      POSTGRES_PASSWORD: corelia
      POSTGRES_DB: corelia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
volumes:
  pgdata:
